# Generated by Django 4.1 on 2022-10-30 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Classe_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "school_year",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("nom", models.CharField(blank=True, max_length=250, null=True)),
                ("prenom", models.CharField(blank=True, max_length=250, null=True)),
                ("slug", models.SlugField(blank=True, max_length=250, null=True)),
                ("dob", models.DateField(blank=True, default="1980-01-01", null=True)),
                ("pob", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField(default="2018-10-23")),
                ("status", models.BooleanField(default="True")),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=250, null=True)),
                ("prenom", models.CharField(blank=True, max_length=250, null=True)),
                ("slug", models.SlugField(blank=True, max_length=250, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=50
                    ),
                ),
                ("dob", models.DateField(blank=True, default="1980-01-01", null=True)),
                ("pob", models.CharField(blank=True, max_length=250, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
